import { SectionDefinition, PageElement } from "@/types";

export const sectionLibrary: SectionDefinition[] = [
  {
    id: "hero-centered",
    name: "Hero — Centered",
    category: "HERO",
    settings: {
      backgroundColor: "var(--theme-bg)",
      paddingTop: { desktop: "100px", tablet: "80px", mobile: "60px" },
      paddingBottom: { desktop: "100px", tablet: "80px", mobile: "60px" },
      containerWidth: "max-w-5xl",
      flexDirection: "col",
      gap: "24px",
    },
    elements: [
      {
        id: "hero-centered-h1",
        type: "heading",
        props: {
          text: "{{business.name}}",
          fontSize: { desktop: "54px", tablet: "42px", mobile: "36px" },
          fontWeight: "700",
          color: "var(--theme-primary)",
          alignment: "center",
        },
      },
      {
        id: "hero-centered-txt",
        type: "text",
        props: {
          text: "{{business.tagline}}",
          fontSize: { desktop: "18px", tablet: "16px", mobile: "15px" },
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
      {
        id: "hero-centered-btn",
        type: "button",
        props: {
          text: "Contact Us Today",
          url: "mailto:{{business.email}}",
          backgroundColor: "var(--theme-primary)",
          textColor: "var(--theme-bg)",
          paddingX: "28px",
          paddingY: "14px",
          borderRadius: "var(--radius-md)",
          fontSize: "16px",
          alignment: "center",
        },
      },
    ],
  },
  {
    id: "hero-split",
    name: "Hero — Split",
    category: "HERO",
    settings: {
      backgroundColor: "var(--theme-muted)",
      paddingTop: { desktop: "90px", tablet: "70px", mobile: "50px" },
      paddingBottom: { desktop: "90px", tablet: "70px", mobile: "50px" },
      containerWidth: "max-w-7xl",
      flexDirection: "row",
      gap: "40px",
    },
    elements: [
      {
        id: "hero-split-left-col",
        type: "heading",
        props: {
          text: "{{business.name}}",
          fontSize: { desktop: "44px", tablet: "36px", mobile: "32px" },
          fontWeight: "700",
          color: "var(--theme-primary)",
          alignment: "left",
        },
      },
      {
        id: "hero-split-text",
        type: "text",
        props: {
          text: "{{business.tagline}} — {{business.description}}",
          fontSize: "16px",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
      {
        id: "hero-split-button",
        type: "button",
        props: {
          text: "Call Us: {{business.phone}}",
          url: "tel:{{business.phone}}",
          backgroundColor: "var(--theme-primary)",
          textColor: "var(--theme-bg)",
          paddingX: "22px",
          paddingY: "11px",
          borderRadius: "var(--radius-sm)",
          fontSize: "15px",
          alignment: "left",
        },
      },
      {
        id: "hero-split-image",
        type: "image",
        props: {
          src: "{{assets.hero}}",
          alt: "Hero showcase photo",
          width: "100%",
          height: "350px",
          borderRadius: "var(--radius-lg)",
          alignment: "center",
        },
      },
    ],
  },
  {
    id: "hero-image-right",
    name: "Hero — Image Right",
    category: "HERO",
    settings: {
      backgroundColor: "var(--theme-bg)",
      paddingTop: { desktop: "90px", tablet: "75px", mobile: "60px" },
      paddingBottom: { desktop: "90px", tablet: "75px", mobile: "60px" },
      containerWidth: "max-w-7xl",
      flexDirection: "row",
      gap: "48px",
    },
    elements: [
      {
        id: "hero-img-right-title",
        type: "heading",
        props: {
          text: "{{business.name}}",
          fontSize: { desktop: "44px", tablet: "36px", mobile: "32px" },
          fontWeight: "700",
          color: "var(--theme-primary)",
          alignment: "left",
        },
      },
      {
        id: "hero-img-right-text",
        type: "text",
        props: {
          text: "{{business.tagline}}",
          fontSize: "16px",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
      {
        id: "hero-img-right-btn",
        type: "button",
        props: {
          text: "Send Message",
          url: "mailto:{{business.email}}",
          backgroundColor: "var(--theme-primary)",
          textColor: "var(--theme-bg)",
          paddingX: "22px",
          paddingY: "11px",
          borderRadius: "var(--radius-md)",
          fontSize: "15px",
          alignment: "left",
        },
      },
      {
        id: "hero-img-right-media",
        type: "image",
        props: {
          src: "{{assets.hero}}",
          alt: "Visual showcase media",
          width: "100%",
          height: "320px",
          borderRadius: "var(--radius-md)",
          alignment: "center",
        },
      },
    ],
  },
  {
    id: "about-split",
    name: "About — Split",
    category: "ABOUT",
    settings: {
      backgroundColor: "var(--theme-bg)",
      paddingTop: { desktop: "80px", tablet: "60px", mobile: "40px" },
      paddingBottom: { desktop: "80px", tablet: "60px", mobile: "40px" },
      containerWidth: "max-w-5xl",
      flexDirection: "row",
      gap: "48px",
    },
    elements: [
      {
        id: "about-split-img",
        type: "image",
        props: {
          src: "{{assets.image_0}}",
          alt: "Our creative space",
          width: "100%",
          height: "320px",
          borderRadius: "var(--radius-md)",
          alignment: "center",
        },
      },
      {
        id: "about-split-heading",
        type: "heading",
        props: {
          text: "About {{business.name}}",
          fontSize: { desktop: "32px", tablet: "28px", mobile: "24px" },
          fontWeight: "700",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
      {
        id: "about-split-text",
        type: "text",
        props: {
          text: "{{business.description}}",
          fontSize: "15px",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
    ],
  },
  {
    id: "about-centered",
    name: "About — Centered",
    category: "ABOUT",
    settings: {
      backgroundColor: "var(--theme-muted)",
      paddingTop: { desktop: "80px", tablet: "65px", mobile: "50px" },
      paddingBottom: { desktop: "80px", tablet: "65px", mobile: "50px" },
      containerWidth: "max-w-4xl",
      flexDirection: "col",
      gap: "20px",
    },
    elements: [
      {
        id: "about-center-title",
        type: "heading",
        props: {
          text: "About Our Philosophy",
          fontSize: "30px",
          fontWeight: "700",
          color: "var(--theme-primary)",
          alignment: "center",
        },
      },
      {
        id: "about-center-p",
        type: "text",
        props: {
          text: "At {{business.name}}, {{business.description}} We are dedicated to delivering standard services designed to scale effectively across all responsive devices.",
          fontSize: "16px",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
    ],
  },
  {
    id: "services-3-cards",
    name: "Services — 3 Cards",
    category: "SERVICES",
    settings: {
      backgroundColor: "var(--theme-bg)",
      paddingTop: { desktop: "80px", tablet: "60px", mobile: "40px" },
      paddingBottom: { desktop: "80px", tablet: "60px", mobile: "40px" },
      containerWidth: "max-w-5xl",
      flexDirection: "col",
      gap: "30px",
    },
    elements: [
      {
        id: "serv-3-h",
        type: "heading",
        props: {
          text: "Professional Core Offerings",
          fontSize: { desktop: "36px", tablet: "30px", mobile: "26px" },
          fontWeight: "700",
          color: "var(--theme-primary)",
          alignment: "center",
        },
      },
      {
        id: "serv-3-t",
        type: "text",
        props: {
          text: "Designed & delivered by the team at {{business.name}} to serve your exact requirements.",
          fontSize: "16px",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
      {
        id: "serv-3-card1",
        type: "heading",
        props: {
          text: "Brand Identity Design",
          fontSize: "20px",
          fontWeight: "600",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
      {
        id: "serv-3-txt1",
        type: "text",
        props: {
          text: "Tailored color palettes, custom typography families, curves radius systems, and consistent token grids.",
          fontSize: "14px",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
      {
        id: "serv-3-card2",
        type: "heading",
        props: {
          text: "Next.js Engineering",
          fontSize: "20px",
          fontWeight: "600",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
      {
        id: "serv-3-txt2",
        type: "text",
        props: {
          text: "High performance rendering complete with strict type safety, modular structures, and absolute responsiveness.",
          fontSize: "14px",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
    ],
  },
  {
    id: "services-4-cards",
    name: "Services — 4 Cards",
    category: "SERVICES",
    settings: {
      backgroundColor: "var(--theme-muted)",
      paddingTop: { desktop: "80px", tablet: "60px", mobile: "40px" },
      paddingBottom: { desktop: "80px", tablet: "60px", mobile: "40px" },
      containerWidth: "max-w-5xl",
      flexDirection: "col",
      gap: "24px",
    },
    elements: [
      {
        id: "serv-4-h",
        type: "heading",
        props: {
          text: "What We Offer",
          fontSize: "32px",
          fontWeight: "700",
          color: "var(--theme-primary)",
          alignment: "center",
        },
      },
      {
        id: "serv-4-card1",
        type: "heading",
        props: {
          text: "1. Consultation",
          fontSize: "18px",
          fontWeight: "600",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
      {
        id: "serv-4-card2",
        type: "heading",
        props: {
          text: "2. Token Mapping",
          fontSize: "18px",
          fontWeight: "600",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
      {
        id: "serv-4-card3",
        type: "heading",
        props: {
          text: "3. Layout Strategy",
          fontSize: "18px",
          fontWeight: "600",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
      {
        id: "serv-4-card4",
        type: "heading",
        props: {
          text: "4. Deployment",
          fontSize: "18px",
          fontWeight: "600",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
    ],
  },
  {
    id: "testimonials",
    name: "Testimonials",
    category: "SOCIAL",
    settings: {
      backgroundColor: "var(--theme-muted)",
      paddingTop: { desktop: "70px", tablet: "55px", mobile: "40px" },
      paddingBottom: { desktop: "70px", tablet: "55px", mobile: "40px" },
      containerWidth: "max-w-3xl",
      flexDirection: "col",
      gap: "20px",
    },
    elements: [
      {
        id: "testi-quote",
        type: "heading",
        props: {
          text: "“By compiling web pages from cohesive design token frameworks, {{business.name}} bypasses raw style overrides entirely and delivers visual consistency layouts.”",
          fontSize: { desktop: "24px", tablet: "20px", mobile: "18px" },
          fontWeight: "600",
          color: "var(--theme-primary)",
          alignment: "center",
        },
      },
      {
        id: "testi-author",
        type: "text",
        props: {
          text: "— Elizabeth Reider, Lead Visual Architect",
          fontSize: "14px",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
    ],
  },
  {
    id: "client-logos",
    name: "Client Logos",
    category: "SOCIAL",
    settings: {
      backgroundColor: "var(--theme-bg)",
      paddingTop: "40px",
      paddingBottom: "40px",
      containerWidth: "max-w-5xl",
      flexDirection: "row",
      gap: "24px",
    },
    elements: [
      {
        id: "logo-lbl",
        type: "text",
        props: {
          text: "Trusted standard partners:",
          fontSize: "14px",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
      {
        id: "logo-t1",
        type: "heading",
        props: {
          text: "ACME",
          fontSize: "20px",
          fontWeight: "800",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
      {
        id: "logo-t2",
        type: "heading",
        props: {
          text: "APEX",
          fontSize: "20px",
          fontWeight: "800",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
      {
        id: "logo-t3",
        type: "heading",
        props: {
          text: "VERTEX",
          fontSize: "20px",
          fontWeight: "800",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
    ],
  },
  {
    id: "features",
    name: "Features",
    category: "CONTENT",
    settings: {
      backgroundColor: "var(--theme-bg)",
      paddingTop: "80px",
      paddingBottom: "80px",
      containerWidth: "max-w-5xl",
      flexDirection: "row",
      gap: "40px",
    },
    elements: [
      {
        id: "feat-left",
        type: "heading",
        props: {
          text: "Engineered For Speed & Refined Performance",
          fontSize: "32px",
          fontWeight: "700",
          color: "var(--theme-primary)",
          alignment: "left",
        },
      },
      {
        id: "feat-right",
        type: "text",
        props: {
          text: "At {{business.name}}, we help clients experience complete visual design control without writing CSS rules from scratch. Experience complete site visualizer power.",
          fontSize: "16px",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
    ],
  },
  {
    id: "stats",
    name: "Stats",
    category: "CONTENT",
    settings: {
      backgroundColor: "var(--theme-muted)",
      paddingTop: "60px",
      paddingBottom: "60px",
      containerWidth: "max-w-4xl",
      flexDirection: "row",
      gap: "24px",
    },
    elements: [
      {
        id: "stat-1-num",
        type: "heading",
        props: {
          text: "150+",
          fontSize: "44px",
          fontWeight: "800",
          color: "var(--theme-primary)",
          alignment: "center",
        },
      },
      {
        id: "stat-1-lbl",
        type: "text",
        props: {
          text: "Projects Delivered",
          fontSize: "14px",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
      {
        id: "stat-2-num",
        type: "heading",
        props: {
          text: "100%",
          fontSize: "44px",
          fontWeight: "800",
          color: "var(--theme-primary)",
          alignment: "center",
        },
      },
      {
        id: "stat-2-lbl",
        type: "text",
        props: {
          text: "Happy Clients",
          fontSize: "14px",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
    ],
  },
  {
    id: "cta",
    name: "CTA",
    category: "CONVERSION",
    settings: {
      backgroundColor: "var(--theme-primary)",
      paddingTop: { desktop: "70px", tablet: "55px", mobile: "40px" },
      paddingBottom: { desktop: "70px", tablet: "55px", mobile: "40px" },
      containerWidth: "max-w-5xl",
      flexDirection: "col",
      gap: "24px",
    },
    elements: [
      {
        id: "cta-h",
        type: "heading",
        props: {
          text: "Ready to Start Your Journey With Us?",
          fontSize: { desktop: "36px", tablet: "30px", mobile: "24px" },
          fontWeight: "700",
          color: "var(--theme-bg)",
          alignment: "center",
        },
      },
      {
        id: "cta-t",
        type: "text",
        props: {
          text: "Get in touch with {{business.name}} and let's craft an aesthetic layout engineered for modular success.",
          fontSize: "16px",
          color: "var(--theme-bg)",
          alignment: "center",
        },
      },
      {
        id: "cta-b",
        type: "button",
        props: {
          text: "Contact Us: {{business.email}}",
          url: "mailto:{{business.email}}",
          backgroundColor: "var(--theme-bg)",
          textColor: "var(--theme-primary)",
          paddingX: "24px",
          paddingY: "12px",
          borderRadius: "var(--radius-md)",
          fontSize: "16px",
          alignment: "center",
        },
      },
    ],
  },
  {
    id: "contact",
    name: "Contact",
    category: "CONVERSION",
    settings: {
      backgroundColor: "var(--theme-bg)",
      paddingTop: "80px",
      paddingBottom: "80px",
      containerWidth: "max-w-5xl",
      flexDirection: "row",
      gap: "40px",
    },
    elements: [
      {
        id: "contact-left-title",
        type: "heading",
        props: {
          text: "Connect With {{business.name}}",
          fontSize: "32px",
          fontWeight: "700",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
      {
        id: "contact-left-desc",
        type: "text",
        props: {
          text: "Address: {{business.address}} \nTel: {{business.phone}} \nEmail: {{business.email}}",
          fontSize: "15px",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
    ],
  },
  {
    id: "simple-navbar",
    name: "Simple Navbar",
    category: "NAVIGATION",
    settings: {
      backgroundColor: "var(--theme-bg)",
      paddingTop: "20px",
      paddingBottom: "20px",
      containerWidth: "max-w-7xl",
      flexDirection: "row",
      gap: "12px",
    },
    elements: [
      {
        id: "nav-brand",
        type: "heading",
        props: {
          text: "{{business.name}}",
          fontSize: "18px",
          fontWeight: "800",
          color: "var(--theme-primary)",
          alignment: "left",
        },
      },
      {
        id: "nav-links",
        type: "text",
        props: {
          text: "About   |   Services   |   Contact   |   Email: {{business.email}}",
          fontSize: "14px",
          color: "var(--theme-foreground)",
          alignment: "center",
        },
      },
      {
        id: "nav-cta",
        type: "button",
        props: {
          text: "Contact Us",
          url: "mailto:{{business.email}}",
          backgroundColor: "var(--theme-primary)",
          textColor: "var(--theme-bg)",
          paddingX: "14px",
          paddingY: "7px",
          borderRadius: "var(--radius-sm)",
          fontSize: "12px",
          alignment: "right",
        },
      },
    ],
  },
  {
    id: "simple-footer",
    name: "Simple Footer",
    category: "FOOTER",
    settings: {
      backgroundColor: "var(--theme-bg)",
      paddingTop: "30px",
      paddingBottom: "30px",
      containerWidth: "max-w-5xl",
      flexDirection: "row",
      gap: "20px",
    },
    elements: [
      {
        id: "foot-cpy",
        type: "text",
        props: {
          text: "© 2026 {{business.name}}. All rights reserved. Completely brand-neutral client visualizer suite. Location: {{business.address}}",
          fontSize: "13px",
          color: "var(--theme-foreground)",
          alignment: "left",
        },
      },
      {
        id: "foot-lnks",
        type: "text",
        props: {
          text: "Privacy Policy | Terms | Email: {{business.email}}",
          fontSize: "13px",
          color: "var(--theme-foreground)",
          alignment: "right",
        },
      },
    ],
  },
];
export default sectionLibrary;
